version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_CONTEXT: application
    ports:
      - 3000:3001
    env_file:
      - .env
    depends_on:
      - mongodb

  mongodb:
    container_name: filecoin-plus-mongodb
    image: mongo:latest
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo_data:/data/db

  toggle:
    image: wiremock/wiremock:3.8.0
    ports:
      - "8080:8080"
    volumes:
      - ./.docker/wiremock:/home/wiremock
    entrypoint:
      [
        "/docker-entrypoint.sh",
        "--global-response-templating",
        "--local-response-templating",
        "--verbose",
      ]

volumes:
  mongo_data:
  rabbitmq_data:
